# Generated by Django 6.0.3 on 2026-04-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_bb_rubric_remove_child_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='rubric',
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, verbose_name='товар'),
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
