# Generated by Django 6.0.3 on 2026-04-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Работа'), ('home', 'Дом'), ('study', 'Учеба')], default='work', max_length=20, verbose_name='Категория'),
        ),
    ]
